# Site settings
title: The Royal Fork
email: rf@royalforkblog.com
description: "A blog about bitcoin."
baseurl: ""
url: "http://royalforkblog.github.io"
twitter_username: royalforkblog

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"
